[2024-07-13T18:57:56.848+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_customers.create_table manual__2024-07-13T13:27:54.354440+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-13T18:58:06.879+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_customers.create_table manual__2024-07-13T13:27:54.354440+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-13T18:58:53.072+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_customers.create_table manual__2024-07-13T13:27:54.354440+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
