[2024-07-14T03:22:33.915+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_bill_payments.create_table manual__2024-07-13T21:52:32.853660+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
