[2024-07-13T18:48:52.116+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_transactions.insert_table manual__2024-07-13T13:18:45.126808+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-13T18:56:27.210+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_transactions.insert_table manual__2024-07-13T13:18:45.126808+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
