[2024-07-12T01:47:49.271+0530] {processor.py:161} INFO - Started process (PID=36649) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:47:49.272+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:47:49.275+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:47:49.275+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:47:49.299+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:47:49.298+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from scripts.raw_load_savings_goals import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'scripts'
[2024-07-12T01:47:49.299+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:47:49.316+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.051 seconds
[2024-07-12T01:48:19.544+0530] {processor.py:161} INFO - Started process (PID=37121) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:19.545+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:48:19.547+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:19.546+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:19.564+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:19.563+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from scripts.raw_load_savings_goals import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'scripts'
[2024-07-12T01:48:19.564+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:19.583+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.045 seconds
[2024-07-12T01:48:51.088+0530] {processor.py:161} INFO - Started process (PID=37504) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:51.088+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:48:51.090+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:51.090+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:51.105+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:51.104+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from scripts.raw_load_savings_goals import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'scripts'
[2024-07-12T01:48:51.106+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:51.128+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.046 seconds
[2024-07-12T01:48:55.918+0530] {processor.py:161} INFO - Started process (PID=37567) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:55.918+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:48:55.920+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:55.920+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:55.947+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:48:55.945+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from models.raw_models.raw_load_savings_goals import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'models'
[2024-07-12T01:48:55.948+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:48:55.979+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.068 seconds
[2024-07-12T01:49:26.379+0530] {processor.py:161} INFO - Started process (PID=38018) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:49:26.380+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:49:26.382+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:49:26.382+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:49:26.400+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:49:26.399+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from models.raw_models.raw_load_savings_goals import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'models'
[2024-07-12T01:49:26.401+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:49:26.419+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.047 seconds
[2024-07-12T01:49:57.305+0530] {processor.py:161} INFO - Started process (PID=38338) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:49:57.306+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:49:57.307+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:49:57.307+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:49:57.325+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:49:57.323+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from models.raw_models.raw_load_savings_goals import create_tables,tuncate_table,insert_table
ModuleNotFoundError: No module named 'models'
[2024-07-12T01:49:57.325+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:49:57.344+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.045 seconds
[2024-07-12T01:50:28.044+0530] {processor.py:161} INFO - Started process (PID=38763) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:50:28.045+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:50:28.047+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:50:28.046+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:50:28.067+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:50:28.066+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from models.raw_models.raw_load_savings_goals import create_tables,tuncate_table,insert_table
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_savings_goals.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-07-12T01:50:28.068+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:50:28.086+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.048 seconds
[2024-07-12T01:50:58.261+0530] {processor.py:161} INFO - Started process (PID=39187) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:50:58.262+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:50:58.263+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:50:58.263+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:50:58.283+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:50:58.282+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from models.raw_models.raw_load_savings_goals import create_tables,tuncate_table,insert_table
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_savings_goals.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-07-12T01:50:58.284+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:50:58.304+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.050 seconds
[2024-07-12T01:51:28.348+0530] {processor.py:161} INFO - Started process (PID=39594) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:51:28.348+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:51:28.350+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:51:28.350+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:51:28.368+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:51:28.366+0530] {dagbag.py:355} ERROR - Failed to import: //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
Traceback (most recent call last):
  File "/home/kali/Desktop/projects/git/bank_data_processing/myenv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py", line 13, in <module>
    from models.raw_models.raw_load_savings_goals import create_tables,tuncate_table,insert_table
  File "//home/kali/Desktop/projects/git/bank_data_processing/dags/models/raw_models/raw_load_savings_goals.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-07-12T01:51:28.368+0530] {processor.py:842} WARNING - No viable dags retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:51:28.385+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.043 seconds
[2024-07-12T01:52:03.753+0530] {processor.py:161} INFO - Started process (PID=40320) to work on //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:52:03.754+0530] {processor.py:830} INFO - Processing file //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py for tasks to queue
[2024-07-12T01:52:03.756+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:03.755+0530] {dagbag.py:545} INFO - Filling up the DagBag from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:52:04.208+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:04.208+0530] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-12T01:52:04.212+0530] {processor.py:840} INFO - DAG(s) 'raw_load_savings_goals' retrieved from //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py
[2024-07-12T01:52:04.313+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:04.312+0530] {override.py:1847} INFO - Created Permission View: can delete on DAG:raw_load_savings_goals
[2024-07-12T01:52:04.324+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:04.324+0530] {override.py:1847} INFO - Created Permission View: can read on DAG:raw_load_savings_goals
[2024-07-12T01:52:04.331+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:04.331+0530] {override.py:1847} INFO - Created Permission View: can edit on DAG:raw_load_savings_goals
[2024-07-12T01:52:04.332+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:04.332+0530] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-12T01:52:04.340+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:04.340+0530] {dag.py:3118} INFO - Creating ORM DAG for raw_load_savings_goals
[2024-07-12T01:52:04.341+0530] {logging_mixin.py:188} INFO - [2024-07-12T01:52:04.341+0530] {dag.py:3954} INFO - Setting next_dagrun for raw_load_savings_goals to None, run_after=None
[2024-07-12T01:52:04.360+0530] {processor.py:183} INFO - Processing //home/kali/Desktop/projects/git/bank_data_processing/dags/dag_raw_savings_goals.py took 0.617 seconds
