[2024-07-16T05:25:31.954+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_customers.tuncate_table manual__2024-07-15T23:55:25.142663+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
