[2024-07-13T16:52:35.630+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_bill_payments.tuncate_table manual__2024-07-13T11:10:20.897160+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
