[2024-07-13T02:01:57.021+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T02:01:57.057+0530] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: parent_dag.trigger_raw_load_accounts manual__2024-07-11T20:36:59.640614+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-12T20:31:57.057445+00:00 and task will be retried at 2024-07-12T20:36:52.851101+00:00.
[2024-07-13T02:01:57.058+0530] {local_task_job_runner.py:163} INFO - Task is not able to be run
[2024-07-13T02:03:23.788+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T02:03:23.816+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parent_dag.trigger_raw_load_accounts manual__2024-07-11T20:36:59.640614+00:00 [queued]>
[2024-07-13T02:03:23.830+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parent_dag.trigger_raw_load_accounts manual__2024-07-11T20:36:59.640614+00:00 [queued]>
[2024-07-13T02:03:23.831+0530] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-07-13T02:03:23.851+0530] {taskinstance.py:2330} INFO - Executing <Task(TriggerDagRunOperator): trigger_raw_load_accounts> on 2024-07-11 20:36:59.640614+00:00
[2024-07-13T02:03:23.857+0530] {standard_task_runner.py:63} INFO - Started process 414778 to run task
[2024-07-13T02:03:23.860+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'parent_dag', 'trigger_raw_load_accounts', 'manual__2024-07-11T20:36:59.640614+00:00', '--job-id', '1181', '--raw', '--subdir', 'DAGS_FOLDER/dag_parent.py', '--cfg-path', '/tmp/tmp641vp3oi']
[2024-07-13T02:03:23.863+0530] {standard_task_runner.py:91} INFO - Job 1181: Subtask trigger_raw_load_accounts
[2024-07-13T02:03:23.910+0530] {task_command.py:426} INFO - Running <TaskInstance: parent_dag.trigger_raw_load_accounts manual__2024-07-11T20:36:59.640614+00:00 [running]> on host kali
[2024-07-13T02:03:23.977+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parent_dag' AIRFLOW_CTX_TASK_ID='trigger_raw_load_accounts' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T20:36:59.640614+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T20:36:59.640614+00:00'
[2024-07-13T02:03:23.979+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T02:03:24.040+0530] {trigger_dagrun.py:222} INFO - Waiting for raw_load_accounts on 2024-07-12 20:33:23.979257+00:00 to become allowed state ['success'] ...
[2024-07-13T02:04:24.046+0530] {trigger_dagrun.py:222} INFO - Waiting for raw_load_accounts on 2024-07-12 20:33:23.979257+00:00 to become allowed state ['success'] ...
[2024-07-13T02:05:24.059+0530] {trigger_dagrun.py:222} INFO - Waiting for raw_load_accounts on 2024-07-12 20:33:23.979257+00:00 to become allowed state ['success'] ...
[2024-07-13T02:06:24.065+0530] {trigger_dagrun.py:222} INFO - Waiting for raw_load_accounts on 2024-07-12 20:33:23.979257+00:00 to become allowed state ['success'] ...
[2024-07-13T02:07:24.070+0530] {trigger_dagrun.py:222} INFO - Waiting for raw_load_accounts on 2024-07-12 20:33:23.979257+00:00 to become allowed state ['success'] ...
[2024-07-13T02:07:41.322+0530] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-07-13T02:07:41.323+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-13T02:07:41.336+0530] {process_utils.py:132} INFO - Sending 15 to group 414778. PIDs of all processes in the group: [414778]
[2024-07-13T02:07:41.336+0530] {process_utils.py:87} INFO - Sending the signal 15 to group 414778
[2024-07-13T02:07:41.337+0530] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-13T02:07:41.337+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T02:07:41.389+0530] {process_utils.py:80} INFO - Process psutil.Process(pid=414778, status='terminated', exitcode=0, started='02:03:23') (414778) terminated with exit code 0
