[2024-07-13T18:48:35.794+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_mortgage_applications.create_table manual__2024-07-13T13:18:33.578325+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-13T18:51:07.471+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_mortgage_applications.create_table manual__2024-07-13T13:18:33.578325+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
