[2024-07-16T05:18:38.435+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_accounts.create_table manual__2024-07-15T23:48:31.090526+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-16T05:19:17.376+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: raw_load_accounts.create_table manual__2024-07-15T23:48:31.090526+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
